# Simple Linear Regression

In [1]:
#1.importing modules

import numpy as np
import matplotlib.pyplot as mtp
import pandas as pd

In [2]:
#2.load data

data_set= pd.read_csv('/content/Salary_Data.csv')
print(data_set.describe())
data_set.head(5)

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [3]:
#3. print data

print("Dataset")
df=pd.DataFrame(data_set)
print(df.to_string())

Dataset
    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
#4. pick columns for x and y

X= data_set.iloc[:, :-1].values  # full rows(:) from 0th column(:1) years of Experience
y = data_set.iloc[:, 1].values # Entire rows from second column(Salary)

print("X=\n",X)
df2=pd.DataFrame(X)
print("X Data-Experience")
print(df2.to_string())
df3=pd.DataFrame(y)
print("Y Data-Salary")
print(df3.to_string())
print("Y array\n")
print(y)

X=
 [[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]
X Data-Experience
       0
0    1.1
1    1.3
2    1.5
3    2.0
4    2.2
5    2.9
6    3.0
7    3.2
8    3.2
9    3.7
10   3.9
11   4.0
12   4.0
13   4.1
14   4.5
15   4.9
16   5.1
17   5.3
18   5.9
19   6.0
20   6.8
21   7.1
22   7.9
23   8.2
24   8.7
25   9.0
26   9.5
27   9.6
28  10.3
29  10.5
Y Data-Salary
           0
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0
Y array

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]

In [6]:
#5.load dataset slicing module

from sklearn.model_selection import train_test_split
# Splitting the dataset into training and test set .
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state=0)

In [8]:
#6.load liniear regression class

from sklearn.linear_model import LinearRegression
#create an instance of linear regression
regressor= LinearRegression()

regressor.fit(x_train, y_train)
x_pred= regressor.predict(x_train)
print("Prediction result on Test Data")
y_pred = regressor.predict(x_test)

dfs=pd.DataFrame(x_test)
print("X-test")
print(dfs)

df2 = pd.DataFrame({'Actual Y-Data': y_test, 'Predicted Y-Data': y_pred})

print(df2.to_string())

print("Mean")
print(df['Salary'].mean())
from sklearn import metrics

print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("Mean")
print(df['Salary'].mean())
from sklearn import metrics

print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

r2_score = regressor.score(x_test,y_test)
print(r2_score*100,'%')

y_pred2 = regressor.predict([[3.5]])
print("exp 3.5")
print(y_pred2)
#print(type(x_test))
arr=np.array([[5.6],[8.0]])
print("arr \n")
print(arr)
y_pred3 = regressor.predict(arr)
print(y_pred3)

Prediction result on Test Data
X-test
      0
0   1.5
1  10.3
2   4.1
3   3.9
4   9.5
5   8.7
   Actual Y-Data  Predicted Y-Data
0        37731.0      40748.961841
1       122391.0     122699.622956
2        57081.0      64961.657170
3        63218.0      63099.142145
4       116969.0     115249.562855
5       109431.0     107799.502753
Mean
76003.0
Root Mean Squared Error: 3580.979237321343
Mean
76003.0
Root Mean Squared Error: 3580.979237321343
98.8169515729126 %
exp 3.5
[59374.11209418]
arr

[[5.6]
 [8. ]]
[ 78930.51986031 101280.70016446]